version: 1.0.{build}

environment:
  global:
    APPVEYOR_OS_NAME: windows
  matrix:
  #MSYS2 Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      BUILDER: MSYS2

  #VisualStudio Building
  #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  #    platform: x86
  #    BUILDER : VS
  #    BITS: 32
  #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  #    platform: x64
  #    BUILDER : VS
  #    BITS: 64

configuration: Debug
shallow_clone: true
clone_depth: 10

init:
- set MSYS2_PATH=c:\msys64
- set CHERE_INVOKING=1
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x86" set MSYSTEM=MINGW32
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x64" set MSYSTEM=MINGW64
- '%MSYS2_PATH%\usr\bin\bash -lc "pacman --noconfirm -S --needed unzip rsync"'
- if "%BUILDER%"=="VS" set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%

install:
- cd ..
- git clone --depth=1 --branch=master https://github.com/openframeworks/openFrameworks
- mkdir openFrameworks\apps\myapps
- move %APPVEYOR_PROJECT_SLUG% openFrameworks\apps\myapps\%APPVEYOR_PROJECT_NAME%
- cd openFrameworks
- if "%BUILDER%"=="MSYS2" %MSYS2_PATH%\usr\bin\bash -lc "scripts/msys2/install_dependencies.sh --noconfirm"
- if "%BUILDER%"=="MSYS2" %MSYS2_PATH%\usr\bin\bash -lc "scripts/msys2/download_libs.sh --silent"
- cd addons
- git clone --depth=1 --branch=develop https://github.com/jvcleave/ofxImGui.git
- cd ..\apps\myapps\%APPVEYOR_PROJECT_NAME%

build_script:
- if "%BUILDER%"=="MSYS2" %MSYS2_PATH%\usr\bin\bash -lc "make Debug && make copy_dlls" 
- if "%BUILDER%"=="VS" echo "BOE" 

after_build:
- cd bin
- 7z a %APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_win_%APPVEYOR_REPO_BRANCH%_%APPVEYOR_REPO_COMMIT%.zip *.*
- dir

deploy:
  provider: FTP
  protocol: sftp
  host: pong.hku.nl
  username: buildbot
  password:
    secure: AABBBCCCCddd123==
  folder: public_html/nightly/
  artifact: buildzip 

artifacts:
  - path: '*.zip'
    name: buildzip
